version: '3'

networks:
  front_network:

services:
  accelerate_frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/development/Dockerfile
    container_name: accelerate_frontend
    volumes:
      - ./:/data
    restart: always
    ports:
      - 9090:9090
    environment:
      - CHOKIDAR_USEPOLLING=true
